server:
  port: 9193

spring:
  application:
    name: EMAIL-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5432/emailservice
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 40
      idle-timeout: 10000
      auto-commit: true
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect
    show-sql: true
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
  mail:
    host: smtp.gmail.com
    port: 587
    username: seuemail@gmail.com
    password: suasenhaaqui
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
